#!/bin/bash
# ============================================================
# Script 5: Open Source Manifesto Generator
# Author: Krish Kumar | Reg No: 24BAI10940
# Course: Open Source Software | Chosen Software: Python
# Purpose: Interactively asks the user 3 questions, then
#          composes and saves a personalised open-source
#          philosophy statement to a .txt file.
# Concepts: read (user input), string concatenation,
#           writing to file with >, date command,
#           alias concept (demonstrated via comment).
# ============================================================

# -------------------------------------------------------
# ALIAS CONCEPT (demonstration via comment):
# In a real shell session you could run:
#   alias manifesto='./script5_manifesto_generator.sh'
# Then type 'manifesto' instead of the full script name.
# Aliases are shortcuts — the open-source equivalent of
# giving a tool a friendlier name for daily use.
# -------------------------------------------------------

# --- Clear screen for a clean experience ---
clear

echo "============================================================"
echo "       OPEN SOURCE MANIFESTO GENERATOR                      "
echo "       Powered by: Python & Bash | OSS Capstone Project     "
echo "============================================================"
echo ""
echo "  This tool will generate your personal open-source"
echo "  philosophy statement based on your answers."
echo ""
echo "  Answer honestly — this is about YOUR relationship"
echo "  with open-source software."
echo ""
echo "------------------------------------------------------------"

# -------------------------------------------------------
# SECTION 1: Interactive input using 'read'
# read -p displays a prompt and waits for user input.
# The answer is stored in the variable after -p "...".
# -------------------------------------------------------

# Question 1: An OSS tool they use daily
read -p "  Q1. Name one open-source tool you use every day: " TOOL
echo ""

# Validate that they typed something (not just hit Enter)
while [ -z "$TOOL" ]; do
    echo "  [Please enter a tool name — e.g., Python, Git, Firefox]"
    read -p "  Q1. Name one open-source tool you use every day: " TOOL
    echo ""
done

# Question 2: What freedom means to them
read -p "  Q2. In one word, what does 'freedom' mean to you? " FREEDOM
echo ""

while [ -z "$FREEDOM" ]; do
    echo "  [Please enter one word — e.g., choice, openness, power]"
    read -p "  Q2. In one word, what does 'freedom' mean to you? " FREEDOM
    echo ""
done

# Question 3: Something they would build and share
read -p "  Q3. Name one thing you would build and share freely: " BUILD
echo ""

while [ -z "$BUILD" ]; do
    echo "  [Please enter something — e.g., a learning app, a tool, a game]"
    read -p "  Q3. Name one thing you would build and share freely: " BUILD
    echo ""
done

echo "------------------------------------------------------------"
echo ""

# -------------------------------------------------------
# SECTION 2: Gather metadata for the manifesto
# We capture date, username, and chosen software to
# personalise the output document.
# -------------------------------------------------------

DATE=$(date '+%d %B %Y')              # Formatted submission date
TIME=$(date '+%H:%M:%S')              # Current time for timestamp
USER=$(whoami)                         # Current Linux username
HOSTNAME=$(hostname)                   # System name for context

# -------------------------------------------------------
# SECTION 3: Compose the manifesto via string concatenation
# We build the manifesto paragraph by combining the user's
# answers with fixed philosophical framing text.
# Each >> appends a new line to the output file.
# The first > creates (or overwrites) the file.
# -------------------------------------------------------

# Output filename — personalised per user
OUTPUT="manifesto_${USER}.txt"

# --- Write the manifesto to file ---

# Header block (> creates/overwrites the file)
echo "============================================================" > "$OUTPUT"
echo "              MY OPEN SOURCE MANIFESTO                      " >> "$OUTPUT"
echo "============================================================" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  Generated by : $USER on $HOSTNAME" >> "$OUTPUT"
echo "  Date         : $DATE at $TIME" >> "$OUTPUT"
echo "  OSS Project  : Python (PSF License)" >> "$OUTPUT"
echo "  Course       : Open Source Software Capstone" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "------------------------------------------------------------" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# --- Core manifesto paragraph (string concatenation across lines) ---
# We compose a flowing paragraph using the user's three answers.
MANIFESTO_PARA="Every day, I rely on $TOOL — a piece of software that was"
MANIFESTO_PARA="$MANIFESTO_PARA built not to be sold, but to be shared."
MANIFESTO_PARA="$MANIFESTO_PARA To me, open source is about $FREEDOM."
MANIFESTO_PARA="$MANIFESTO_PARA It is the belief that knowledge grows stronger when"
MANIFESTO_PARA="$MANIFESTO_PARA it is given away, not locked behind a price or a"
MANIFESTO_PARA="$MANIFESTO_PARA permission slip. The developers who built $TOOL chose"
MANIFESTO_PARA="$MANIFESTO_PARA to place it in the hands of the world — and because"
MANIFESTO_PARA="$MANIFESTO_PARA they did, I have been able to learn, build, and create."

echo "  $MANIFESTO_PARA" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# --- Second paragraph: forward-looking commitment ---
PARA2="If I were to build something today, it would be $BUILD."
PARA2="$PARA2 And I would share it — without restriction, without"
PARA2="$PARA2 reservation — because the tools I have inherited from"
PARA2="$PARA2 the open-source community were shared with me in exactly"
PARA2="$PARA2 that spirit. Python, the software I have studied in this"
PARA2="$PARA2 project, embodies this philosophy completely. Its license"
PARA2="$PARA2 asks nothing in return for commercial use. Its community"
PARA2="$PARA2 asks only that you continue: learn, build, share, repeat."

echo "  $PARA2" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# --- Closing signature ---
echo "------------------------------------------------------------" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  Signed: $USER" >> "$OUTPUT"
echo "  Date  : $DATE" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  'Given enough eyeballs, all bugs are shallow.'" >> "$OUTPUT"
echo "  — Eric S. Raymond, The Cathedral and the Bazaar" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "============================================================" >> "$OUTPUT"

# -------------------------------------------------------
# SECTION 4: Confirm and display the manifesto
# cat reads and prints the file contents to the terminal.
# -------------------------------------------------------

echo ""
echo "  [SUCCESS] Your manifesto has been saved to: $OUTPUT"
echo ""
echo "------------------------------------------------------------"
echo "  PREVIEW:"
echo "------------------------------------------------------------"
echo ""

# Display the file we just created
cat "$OUTPUT"

echo ""
echo "------------------------------------------------------------"
echo "  File saved as: $(pwd)/$OUTPUT"
echo "  Submit this file alongside your report on VITyarthi."
echo "============================================================"
